### PR TITLE
Add VS Code Devcontainer config

### PR DESCRIPTION
**Pull request by joeriddles**
Related docs
- https://code.visualstudio.com/docs/devcontainers/create-dev-container
- https://containers.dev/

### CODE REVIEW

**Comment by joeriddles** [comment]
@tim-schilling please take a look when you get a chance!

**Review by tim-schilling — APPROVED** [review]
Looks good to me.

**Comment by tim-schilling** [comment]
@joeriddles you should have permissions to merge this in too.

**Comment by joeriddles** [comment]
Re-committed with a GPG key configured.

**Pull request merged**
